version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "microservice-cart"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-z2rhh0echgwp"
s3_prefix = "microservice-cart"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
