AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  microservice-cart

  Sample SAM Template for microservice-cart

###################################################################################################
##  Template Parameters                                                                         ##
###################################################################################################
Parameters:
  ClientDomains:
    Type: CommaDelimitedList
    Description: Array of domains allowed to use the API
    Default: '*'

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  MicroserviceCartFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: microservice/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref DynamoDBTable        
      Events:
        MicroserviceGetCart:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /cart
            Method: get
            ApiId: !Ref HttpApi
        MicroservicePutCart:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /cart
            Method: put
            ApiId: !Ref HttpApi
      Environment:
        Variables:
          PRODUCT_TABLE: !Ref DynamoDBTable
          
  ##  API Gateway
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowMethods:
          - GET
        AllowHeaders: 
          - '*'
        AllowOrigins: !Ref ClientDomains
  
  ##  Cart Table
  DynamoDBTable:
    Type: 'AWS::DynamoDB::Table'
    DeletionPolicy: Delete
    Properties:
      AttributeDefinitions:
        -
          AttributeName: id
          AttributeType: N
      KeySchema:
        -
          AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HttpApiUrl:
    Description: URL of your API endpoint
    Value:
        Fn::Sub: 'https://${HttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}'
  DynamoDBTableName:
    Description: The name of your DynamoDB table
    Value: !Ref DynamoDBTable
  MicroserviceCartFunction:
    Description: "Micro service Cart Lambda Function ARN"
    Value: !GetAtt MicroserviceCartFunction.Arn
  MicroserviceCartFunctionIamRole:
    Description: "Implicit IAM Role created for Microservice Cart function"
    Value: !GetAtt MicroserviceCartFunctionRole.Arn
